name = "shy-sea-600a"
main = "src/index.js"
compatibility_date = "2026-01-09"
workers_dev = true

routes = [
  { pattern = "alfredmayaki.me/chat*", zone_name = "alfredmayaki.me" },
  { pattern = "www.alfredmayaki.me/chat*", zone_name = "alfredmayaki.me" }
]

[vars]
GEMINI_MODEL = "chat-bison-001"
GEMINI_API_VERSION = "v1"